root = "."
tmp_dir = ".tmp"

[build]
  bin = "bin/blog-debug"
  full_bin = "./bin/blog-debug"
  cmd = "mage build:dev"
  delay = 0
  exclude_dir = ["logs", "bin", "node_modules", "assets/css"]
  exclude_file = ["Dockerfile", "docker-compose.yaml", "mage_output_file.go"]
  exclude_regex = ["_test\\.go", "\\.null-ls", "_templ\\.go"]
  follow_symlink = false
  include_ext = ["go", "templ", "md", "js", "css"]
  stop_on_error = true
  log = "logs/build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
