// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

type Comment struct {
	ID           int64
	LookupID     string
	UserID       int64
	CreatedAt    string
	UpdatedAt    string
	ArticleSlug  string
	PublishedAt  string
	ApprovedAt   *string
	ApprovalCode string
	ShouldNotify bool
	Content      string
}

type User struct {
	ID           int64
	CreatedAt    string
	UpdatedAt    string
	FirebaseUid  string
	Email        string
	Name         string
	ShouldNotify bool
	IsBanned     bool
	IsAdmin      bool
}
